### ISSUE TITLE
Angle Plugin does not work on Sketch 66

### ISSUE THREAD

**Issue by GolrizB** [MengTo/Angle-Sketch-Plugin#53]

**Comment by GolrizB** [comment]
the command \ does not work.

**Comment by mgeyersfdc** [comment]
I'm seeing this as well :(

**Comment by pungme** [comment]
I'm having the same issue. Will downgrade to 65 for now

**Comment by mlobien** [comment]
I'm seeing this also :(

**Comment by pepijndesign** [comment]
Same problem here.

**Comment by FelixTraxler** [comment]
Same problem

**Comment by lamollner** [comment]
Same problem.

**Comment by adcruz01** [comment]
Does not work on this latest Sketch update. When can we expect a fix?

**Comment by rodi01** [comment]
In case you need more info on this, here is the error from the console 
```
ReferenceError: Can't find variable: MSImmutableLayerAncestry
    at /Users/rodrigo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Angle.sketchplugin/Contents/Sketch/apply.js:1:21216
    at map[native code] (/)
    at u (/Users/rodrigo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Angle.sketchplugin/Contents/Sketch/apply.js:1:17418)
    at /Users/rodrigo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Angle.sketchplugin/Contents/Sketch/apply.js:1:15214
    at /Users/rodrigo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Angle.sketchplugin/Contents/Sketch/apply.js:1:15639
    at __skpm_run (/Users/rodrigo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Angle.sketchplugin/Contents/Sketch/apply.js:1:27833)
    at __skpm_run[native code] (/)
```

**Comment by MrBenjaminJones** [comment]
If this is helpful - Looks like MSImmutableLayerAncestry has been renamed to SketchModel.MSImmutableLayerAncestry in Sketch 66. 
https://sketchplugins.com/d/2061-sketch-66-msimmutablelayerancestry

**Comment by 5kylar** [comment]
Same problem.

**Comment by ksellsworth** [comment]
Same problem

**Comment by JunhyeopSong** [comment]
Same problem

**Comment by Samaing1983** [comment]
Here a new updated version plugin https://github.com/MengTo/Angle-Sketch-Plugin/tree/sketch-66-modal. Make sure to read the instructions.

**Comment by JunhyeopSong** [comment]
> Here a new updated version plugin https://github.com/MengTo/Angle-Sketch-Plugin/tree/sketch-66-modal. Make sure to read the instructions.

Thanks! updated plugin is working well now.
